Repository OWASP/Nettacker, pull requests merged in 2018-06, with the labels that each got.

#151 Added Xdebug vuln module and added service scanners signatures
  core/attack.py
  lib/payload/scanner/service/engine.py
  lib/vuln/xdebug_rce/__init__.py
  lib/vuln/xdebug_rce/engine.py
  requirements.txt
Labels: enhancement

#153 Completing CMS Scanner for Drupal
  lib/scan/drupal_modules/__init__.py
  lib/scan/drupal_modules/engine.py
  lib/scan/drupal_theme/__init__.py
  lib/scan/drupal_theme/engine.py
  lib/scan/drupal_version/__init__.py
  lib/scan/drupal_version/engine.py
Labels: enhancement

#156 UDP Port scan with service names
  lib/scan/port/engine.py
Labels: enhancement

#159 Bug Fix setup.py
  requirements.txt
  setup.py
Labels: bug, bug fixed, enhancement

#170 Replace viraintel with zdresearch
  CONTRIBUTING.md
  lib/graph/d3_tree_v1/engine.py
  lib/graph/jit_circle_v1/engine.py
  lib/language/messages_ar.py
  lib/language/messages_de.py
  lib/language/messages_el.py
  lib/language/messages_en.py
  lib/language/messages_es.py
  lib/language/messages_fa.py
  lib/language/messages_fr.py
  lib/language/messages_hi.py
  lib/language/messages_hy.py
  lib/language/messages_id.py
  lib/language/messages_it.py
  lib/language/messages_iw.py
  lib/language/messages_ja.py
  lib/language/messages_ko.py
  lib/language/messages_nl.py
  lib/language/messages_ps.py
  lib/language/messages_ru.py
  lib/language/messages_tr.py
  lib/language/messages_ur.py
  lib/language/messages_vi.py
  lib/language/messages_zh-cn.py
  lib/payload/shellcode/readme.md
  lib/vuln/wordpress_dos_cve_2018_6389/engine.py
  readme.md
  setup.py
  web/static/index.html
Labels: enhancement

#167 Solve issue#165
  core/log.py
  database/db.py
  lib/language/messages_en.py
Labels: enhancement

#166 Complete the tutorial using introJs for WebView
  web/static/css/introjs-dark.css
  web/static/css/introjs-flattener.css
  web/static/css/introjs-modern.css
  web/static/css/introjs-nassim.css
  web/static/css/introjs-nazanin.css
  web/static/css/introjs-royal.css
  web/static/css/introjs-rtl.min.css
  web/static/css/introjs.min.css
  web/static/css/style.css
  web/static/index.html
  web/static/js/intro.min.js
  web/static/js/main.js
Labels: done, enhancement

#173 Fix #172
  lib/http_fuzzer/engine.py
Labels: bug fixed, done

#175 Add license for intro.js
  EXTERNAL_LIBRARIES_LICENSES.md
Labels: enhancement
