Repository OWASP/Nettacker, pull requests merged in 2018-03, with the labels that each got.

#54 Admin scanner
  lib/scan/admin/__init__.py
  lib/scan/admin/engine.py
Labels: enhancement

#55 181:admin_scan
  lib/language/messages_en.py
Labels: enhancement

#56 Weak Encryption algo, self signed certificate, ccs injection and ssl certificate expired vulnerability.
  lib/vuln/CCS_injection/__init__.py
  lib/vuln/CCS_injection/engine.py
  lib/vuln/self_signed_certificate/__init__.py
  lib/vuln/self_signed_certificate/engine.py
  lib/vuln/ssl_certificate_expired/__init__.py
  lib/vuln/ssl_certificate_expired/engine.py
  lib/vuln/weak_signature_algorithm/__init__.py
  lib/vuln/weak_signature_algorithm/engine.py
Labels: enhancement

#57 Add telnet_brute module
  lib/brute/telnet/__init__.py
  lib/brute/telnet/engine.py
  lib/language/messages_en.py
Labels: enhancement

#58 Add http brute modules
  lib/brute/http_basic_auth/__init__.py
  lib/brute/http_basic_auth/engine.py
  lib/brute/http_form/__init__.py
  lib/brute/http_form/engine.py
  lib/brute/http_ntlm/__init__.py
  lib/brute/http_ntlm/engine.py
  lib/language/messages_en.py
Labels: enhancement

#59 Multiple FTP vulnerabilities
  lib/scan/port/engine.py
  lib/vuln/Bftpd_double_free/__init__.py
  lib/vuln/Bftpd_double_free/engine.py
  lib/vuln/Bftpd_memory_leak/__init__.py
  lib/vuln/Bftpd_memory_leak/engine.py
  lib/vuln/Bftpd_parsecmd_overflow/__init__.py
  lib/vuln/Bftpd_parsecmd_overflow/engine.py
  lib/vuln/Bftpd_remote_dos/__init__.py
  lib/vuln/Bftpd_remote_dos/engine.py
  lib/vuln/ProFTPd_bypass_sqli_protection/__init__.py
  lib/vuln/ProFTPd_bypass_sqli_protection/engine.py
  lib/vuln/ProFTPd_cpu_consumption/__init__.py
  lib/vuln/ProFTPd_cpu_consumption/engine.py
  lib/vuln/ProFTPd_directory_traversal/__init__.py
  lib/vuln/ProFTPd_directory_traversal/engine.py
  lib/vuln/ProFTPd_exec_arbitary/__init__.py
  lib/vuln/ProFTPd_exec_arbitary/engine.py
Labels: enhancement

#63 Update readme to include newer methods
  readme.md
Labels: enhancement

#64 Adds wappalyzer scan module
  lib/language/messages_en.py
  lib/scan/wappalyzer/__init__.py
  lib/scan/wappalyzer/apps.json
  lib/scan/wappalyzer/engine.py
Labels: enhancement

#72 Language Fix
  api/__database.py
  api/api_core.py
  api/engine.py
  core/alert.py
  core/args_loader.py
  core/attack.py
  core/compatible.py
  core/ip.py
  core/load_modules.py
  core/log.py
  core/parse.py
  core/targets.py
  core/update.py
  core/wizard.py
  lib/argparse/__init__.py
  lib/brute/ftp/engine.py
  lib/brute/http_basic_auth/engine.py
  lib/brute/http_form/engine.py
  lib/brute/http_ntlm/engine.py
  lib/brute/smtp/engine.py
  lib/brute/ssh/engine.py
  lib/brute/telnet/engine.py
  lib/graph/d3_tree_v1/engine.py
  lib/graph/jit_circle_v1/engine.py
  lib/language/messages_en.py
  lib/scan/admin/engine.py
  lib/scan/dir/engine.py
  lib/scan/icmp/engine.py
  lib/scan/pma/engine.py
  lib/scan/port/engine.py
  lib/scan/subdomain/engine.py
  lib/scan/viewdns_reverse_ip_lookup/engine.py
  lib/scan/wappalyzer/engine.py
  lib/vuln/Bftpd_double_free/engine.py
  lib/vuln/Bftpd_memory_leak/engine.py
  lib/vuln/Bftpd_parsecmd_overflow/engine.py
  lib/vuln/Bftpd_remote_dos/engine.py
  lib/vuln/CCS_injection/engine.py
  lib/vuln/ProFTPd_bypass_sqli_protection/engine.py
  lib/vuln/ProFTPd_cpu_consumption/engine.py
  lib/vuln/ProFTPd_directory_traversal/engine.py
  lib/vuln/ProFTPd_exec_arbitary/engine.py
  lib/vuln/heartbleed/engine.py
  lib/vuln/self_signed_certificate/engine.py
  lib/vuln/ssl_certificate_expired/engine.py
  lib/vuln/weak_signature_algorithm/engine.py
  lib/vuln/wordpress_dos_cve_2018_6389/engine.py
Labels: enhancement

#71 Fixes issue #69
  lib/brute/http_form/engine.py
  requirements.txt
Labels: bug fixed, enhancement

#76 PEP8 Fixes for all the python files
  api/engine.py
  core/load_modules.py
  lib/argparse/v2/argparse.py
  lib/argparse/v3/argparse.py
  lib/brute/ftp/engine.py
  lib/brute/http_basic_auth/engine.py
  lib/brute/http_form/engine.py
  lib/brute/http_ntlm/engine.py
  lib/brute/smtp/engine.py
  lib/brute/ssh/engine.py
  lib/brute/telnet/engine.py
  lib/graph/d3_tree_v1/engine.py
  lib/graph/jit_circle_v1/engine.py
  lib/icmp/engine.py
  lib/language/messages_en.py
  lib/scan/admin/engine.py
  lib/scan/dir/engine.py
  lib/scan/icmp/engine.py
  lib/scan/pma/engine.py
  lib/scan/port/engine.py
  lib/scan/subdomain/engine.py
  lib/scan/viewdns_reverse_ip_lookup/engine.py
  lib/scan/wappalyzer/engine.py
  lib/vuln/Bftpd_double_free/engine.py
  lib/vuln/Bftpd_memory_leak/engine.py
  lib/vuln/Bftpd_parsecmd_overflow/engine.py
  lib/vuln/Bftpd_remote_dos/engine.py
  lib/vuln/CCS_injection/engine.py
  lib/vuln/ProFTPd_bypass_sqli_protection/engine.py
  lib/vuln/ProFTPd_cpu_consumption/engine.py
  lib/vuln/ProFTPd_directory_traversal/engine.py
  lib/vuln/ProFTPd_exec_arbitary/engine.py
  lib/vuln/heartbleed/engine.py
  lib/vuln/self_signed_certificate/engine.py
  lib/vuln/ssl_certificate_expired/engine.py
  lib/vuln/weak_signature_algorithm/engine.py
  lib/vuln/wordpress_dos_cve_2018_6389/engine.py
  scripts/__travis_test__.py
  setup.py
Labels: enhancement

#78 Fixes Issue#74
  core/targets.py
  lib/brute/http_basic_auth/engine.py
Labels: bug fixed

#79 Handle case when no auth
  lib/brute/http_basic_auth/engine.py
  lib/brute/http_form/engine.py
  lib/brute/http_ntlm/engine.py
  lib/language/messages_en.py
Labels: enhancement

#82 Fix minor web UI bugs
  web/static/css/bootstrap.min.css
  web/static/css/style.css
Labels: enhancement

#85 UI Enhancements and update requirements.txt
  api/api_core.py
  lib/scan/wappalyzer/engine.py
  requirements.txt
  web/static/css/bootstrap-tagsinput.css
  web/static/index.html
  web/static/js/angular.min.js
  web/static/js/bootstrap-select.min.js
  web/static/js/bootstrap-tagsinput-angular.min.js
  web/static/js/bootstrap-tagsinput.min.js
  web/static/js/main.js
Labels: enhancement

#86 content Security policy Vuln
  lib/vuln/content_security_policy/__init__.py
  lib/vuln/content_security_policy/engine.py
Labels: enhancement

#89 Minor UI bug fixes
  api/__database.py
  api/api_core.py
  web/static/index.html
  web/static/js/main.js
Labels: bug, bug fixed

#92 Fix #91
  Dockerfile
Labels: bug, bug fixed, enhancement

#93 Server version disclosure
  lib/vuln/server_version/__init__.py
  lib/vuln/server_version/engine.py
  lib/vuln/x_powered_by/__init__.py
  lib/vuln/x_powered_by/engine.py
Labels: enhancement

#95 solve issue #69
  lib/brute/http_form/engine.py
Labels: bug fixed
