Repository OWASP/Nettacker, pull requests merged in 2018-05, with the labels that each got.

#137 Change the pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#136 Joomla username enumeration Scan
  lib/scan/joomla_user_enum/__init__.py
  lib/scan/joomla_user_enum/engine.py
Labels: enhancement

#142 Added service names in port scan
  lib/scan/port/engine.py
Labels: enhancement

#140 Migration to sqlalchemy
  api/engine.py
  core/config.py
  core/config_builder.py
  core/load_modules.py
  core/log.py
  database/__init__.py
  database/db.py
  database/models.py
  database/mysql_create.py
  database/readme.md
  database/sqlite_create.py
  lib/language/messages_en.py
  requirements.txt
Labels: enhancement

#144 Resolved issue #141 and #139
  core/attack.py
  requirements.txt
Labels: bug fixed

#145 Add sqlalchemy to the licences
  EXTERNAL_LIBRARIES_LICENSES.md
Labels: done, enhancement

#146 Resolves Issue #111
  lib/scan/wappalyzer/engine.py
Labels: bug fixed, done

#147 Implement a http fuzzer for nettacker
  core/targets.py
  lib/http_fuzzer/__init__.py
  lib/http_fuzzer/engine.py
  lib/http_fuzzer/readme.md
  lib/language/messages_en.py
  lib/scan/pma/engine.py
Labels: enhancement
