Repository OWASP/Nettacker, pull requests merged in 2018-02, with the labels that each got.

#40 optimze engine
  api/__start_scan.py
  api/api_core.py
  core/args_loader.py
  core/attack.py
  core/config.py
  core/config_builder.py
  core/parse.py
  lib/brute/ftp/engine.py
  lib/brute/smtp/engine.py
  lib/brute/ssh/engine.py
  lib/language/messages_en.py
  lib/scan/dir/engine.py
  lib/scan/pma/engine.py
  lib/scan/port/engine.py
  lib/vuln/heartbleed/engine.py
  lib/vuln/wordpress_dos_cve_2018_6389/engine.py
Labels: updates from dev

#45 Fixes multiple import issue in pma_scan
  lib/scan/pma/engine.py
Labels: bug, enhancement

#47 Add icmp_scan module
  lib/language/messages_en.py
  lib/scan/icmp/__init__.py
  lib/scan/icmp/engine.py
Labels: enhancement

#50 Fixes issue #48
  lib/brute/ftp/engine.py
  lib/brute/smtp/engine.py
  lib/brute/ssh/engine.py
  lib/scan/dir/engine.py
  lib/scan/port/engine.py
  lib/scan/subdomain/engine.py
  lib/vuln/heartbleed/engine.py
  lib/vuln/wordpress_dos_cve_2018_6389/engine.py
Labels: enhancement
