Repository OWASP/Nettacker, pull requests merged in 2018-04, with the labels that each got.

#96 Password List Generator
  lib/payload/password/generator/__init__.py
  lib/payload/password/generator/engine.py
  lib/payload/password/generator/readme.md
  lib/payload/readme.md
  lib/scan/joomla_version/__init__.py
  lib/scan/joomla_version/engine.py
  lib/scan/wp_theme/small_themes.py
Labels: done, enhancement

#102 WordPress, joomla and SPF record check modules
  lib/brute/wp_xmlrpc/__init__.py
  lib/brute/wp_xmlrpc/engine.py
  lib/scan/joomla_template/__init__.py
  lib/scan/joomla_template/engine.py
  lib/scan/sender_policy/__init__.py
  lib/scan/sender_policy/engine.py
  lib/scan/wp_timthumbs/__init__.py
  lib/scan/wp_timthumbs/engine.py
  lib/scan/wp_timthumbs/wp_timthumbs.py
  requirements.txt
  setup.py
Labels: enhancement

#104 Resolves Issue#103
  api/api_core.py
  core/config.py
Labels: enhancement

#109 Update the new link in readme
  readme.md
Labels: done, enhancement

#108 Requirements updated with version
  requirements.txt
Labels: done, enhancement

#105 HTTPS Target Type & Stealth Scan
  lib/scan/port/engine.py
  lib/vuln/apache_struts/engine.py
Labels: bug

#110 Now http://website.com as well as http://website.com/ both are recognized by nettacker correctoly and no error comes.
  core/targets.py
Labels: done, enhancement
