Repository OWASP/Nettacker, pull requests merged in 2021-03, with the labels that each got.

#406 Add CVE-2021-26855 vuln module
  lib/vuln/msexchange_cve_2021_26855/__init__.py
  lib/vuln/msexchange_cve_2021_26855/engine.py
Labels: new module

#410 fixed XSS
  api/engine.py
Labels: bug fixed

#330 Added JSON and CSV download links
  api/engine.py
  web/static/js/main.js
Labels: enhancement

#391 Fix #390
  lib/vuln/content_security_policy/engine.py
Labels: enhancement

#367 added graphql module
  lib/language/messages_en.py
  lib/payload/wordlists/graphql.py
  lib/vuln/graphql/__init__.py
  lib/vuln/graphql/engine.py
Labels: new module

#286 Added xmlrpc_scan module
  lib/transactions/maltego/nettacker_transforms/src/nettacker_transforms/transforms/wp_xmlrpc_dos_vuln.py
  lib/vuln/wp_xmlrpc_dos/__init__.py
  lib/vuln/wp_xmlrpc_dos/engine.py
Labels: new module

#414 fixed ccs injection import
  requirements.txt
Labels: merge conflict, merge conflict resolved
