Repository OWASP/Nettacker, pull requests merged in 2024-09, with the labels that each got.

#876 Added SSL/TLS Modules
  docs/Events.md
  docs/Modules.md
  nettacker/core/lib/ssl.py
  nettacker/core/module.py
  nettacker/modules/scan/ssl_expiring_certificate.yaml
  nettacker/modules/vuln/ssl_certificate_weak_signature.yaml
  nettacker/modules/vuln/ssl_expired_certificate.yaml
  nettacker/modules/vuln/ssl_self_signed_certificate.yaml
  nettacker/modules/vuln/ssl_weak_cipher.yaml
  nettacker/modules/vuln/ssl_weak_version.yaml
  tests/core/test_socket.py
  tests/core/test_ssl.py
Labels: gsoc

#877 Added Scan Compare feature
  nettacker/api/engine.py
  nettacker/config.py
  nettacker/core/app.py
  nettacker/core/arg_parser.py
  nettacker/core/graph.py
  nettacker/core/utils/common.py
  nettacker/database/db.py
  nettacker/lib/compare_report/__init__.py
  nettacker/lib/compare_report/engine.py
  nettacker/locale/en.yaml
  nettacker/web/static/css/style.css
  nettacker/web/static/index.html
  nettacker/web/static/js/main.js
  nettacker/web/static/report/compare_report.html
Labels: gsoc

#909 dir_scan module
  nettacker/core/lib/http.py
  nettacker/lib/payloads/wordlists/dir_wordlist.txt
  nettacker/modules/scan/dir.yaml
Labels: new module

#911 ivanti_csa_lastpatcheddate_scan module
  docs/Modules.md
  nettacker/modules/scan/ivanti_csa_lastpatcheddate.yaml
Labels: new module

#918 new module: ivanti_vtm_version_scan
  nettacker/modules/scan/ivanti_vtm_version.yaml
Labels: new module

#922 add ivanti_vtm_version_scan to docs
  docs/Modules.md
Labels: documentation

#923 Update docs Installation.md for 0.4.0
  docs/Installation.md
Labels: documentation
