Repository OWASP/Nettacker, pull requests merged in 2025-08, with the labels that each got.

#1113 [Feature-Web] adding skipping service discovery, exclude ports and custom HTTP headers to the web
  nettacker/api/engine.py
  nettacker/web/static/index.html
  nettacker/web/static/js/main.js
Labels: enhancement

#1117 Fixed the issue of select all profiles button
  nettacker/web/static/index.html
  nettacker/web/static/js/main.js
Labels: bug fixed

#1121 Readme update with updated text, docker commands +docker-compose update
  README.md
  docker-compose.yml
Labels: Docker, documentation

#1125 New module: adobe_aem_lastpatcheddate_scan
  docs/Modules.md
  nettacker/modules/scan/adobe_aem_lastpatcheddate.yaml
Labels: new module
