Repository OWASP/Nettacker, pull requests merged in 2025-07, with the labels that each got.

#1098 Updating regex for strict_transport_security_vuln
  nettacker/modules/vuln/strict_transport_security.yaml
Labels: bug fixed

#1107 [feature] add custom headers for http requests via CLI and remove sensitive headers before adding it to the database
  docs/Usage.md
  nettacker/config.py
  nettacker/core/arg_parser.py
  nettacker/core/lib/base.py
  nettacker/core/lib/http.py
  nettacker/core/utils/common.py
  nettacker/locale/en.yaml
  poetry.lock
  pyproject.toml
  tests/core/lib/test_user_added_http_headers.py
Labels: enhancement, gsoc

#1109 New module to detect PaloAlto GlobalProtect XSS CVE-2025-0133
  docs/Modules.md
  nettacker/modules/vuln/paloalto_globalprotect_cve_2025_0133.yaml
Labels: new module
